apiVersion: v1
kind: Namespace
metadata:
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-20"
    "helm.sh/resource-policy": keep
  labels:
    app: spectro
    module: hubble
    spectrocloud.com/imageswap: "enabled"
  name: frontend
